language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

script:
  # The dependency ipython uses requirement markers that are not understood
  # by setuptools 12.0.5 which is the current version in the default Travis-CI
  # environment.
  - pip install --upgrade setuptools
  - python bootstrap.py
  - ./bin/buildout
