language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - RDFLIB_VERSION=3.0.0
  - RDFLIB_VERSION=3.1.0
  - RDFLIB_VERSION=3.2.0
  - RDFLIB_VERSION=3.2.1
  - RDFLIB_VERSION=3.2.2
  - RDFLIB_VERSION=3.2.3
  - RDFLIB_VERSION=3.4.0

  - RDFLIB_VERSION=2.4.1
  - RDFLIB_VERSION=4.2.1

matrix:
  exclude:
    # Python 3 support started with rdflib 3.2.0
    - python: 3.3
      env: RDFLIB_VERSION=2.4.1
    - python: 3.3
      env: RDFLIB_VERSION=3.0.0
    - python: 3.3
      env: RDFLIB_VERSION=3.1.0
    - python: 3.4
      env: RDFLIB_VERSION=2.4.1
    - python: 3.4
      env: RDFLIB_VERSION=3.0.0
    - python: 3.4
      env: RDFLIB_VERSION=3.1.0
    - python: 3.5
      env: RDFLIB_VERSION=2.4.1
    - python: 3.5
      env: RDFLIB_VERSION=3.0.0
    - python: 3.5
      env: RDFLIB_VERSION=3.1.0

  allow_failures:
    - env: RDFLIB_VERSION=2.4.1
    - env: RDFLIB_VERSION=4.2.1

install:
  # The dependency ipython uses requirement markers that are not understood
  # by setuptools 12.0.5 which is the current version in the default Travis-CI
  # environment.
  - pip install --upgrade setuptools
  - pip install rdflib=="$RDFLIB_VERSION"
  - python bootstrap.py
  - ./bin/buildout

script:
  - ./bin/genanzsrc
